server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sensordb
    username: s_user
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    temp:
      use_jdbc_metadata_defaults: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
